version: "3.8"
networks:
  my_network:
    external: true
services:


################################################################



################################################################

  
################################################################

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - /root/docker/homepage:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock:ro # optional, for docker integrations
    restart: unless-stopped
    networks:
      my_network:
        ipv4_address:



################################################################



################################################################



################################################################


  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /root/docker/lidarr:/config
      - /home/ubuntu/Onedrive/Plex/music:/music #optional
    ports:
      - 8686:8686
    restart: unless-stopped

###########################################################

  glances:
    container_name: glances
    image: nicolargo/glances:latest
    restart: always
    pid: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - "GLANCES_OPT=-w"
    ports:
      - 61208:61208
    labels:
      - "traefik.port=61208"
      - "traefik.frontend.rule=Host:glances.docker.localhost"

#######################################################

  organizr:
    image: organizr/organizr:latest
    container_name: organizr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - /root/docker/organizr:/config
    ports:
      - 9983:80
    restart: unless-stopped

##########################################################

  wizarr:
    container_name: wizarr
    image: ghcr.io/wizarrrr/wizarr:latest
    #user: 1000:1000 #Optional but recommended, sets the user uid that Wizarr will run with
    ports:
      - 5690:5690
    volumes:
      - /root/docker/wizarr/config:/data/database
    environment:
      - APP_URL= #URL at which you will access and share 
      - DISABLE_BUILTIN_AUTH=false #Set to true ONLY if you are using another auth provider (Authelia, Authentik, etc)
      - TZ=Asia/Kolkata #Set your timezone here

#############################################################

  duckdns:
    image: ghcr.io/linuxserver/duckdns:latest
    container_name: duckdns
    environment:
      - PUID=1000 #optional
      - PGID=1000 #optional
      - TZ=Asia/Kolkata
      - SUBDOMAINS=
      - TOKEN=
      - LOG_FILE=false #optional
    volumes:
      - /root/docker/duckdns/config:/config #optional
    restart: unless-stopped

#################################################################

  couchdb:
    image: couchdb
    container_name: obsidian-livesync
    user: 1000:1000
    environment:
      - COUCHDB_USER=Staging4570
      - COUCHDB_PASSWORD=Spectrum$Strategic$Blouse5
    volumes:
      - ./data:/opt/couchdb/data
      - ./local.ini:/opt/couchdb/etc/local.ini
    ports:
      - 5984:5984
    restart: unless-stopped

###############################################################

  plexautolanguages:
    image: remirigal/plex-auto-languages:latest
    container_name: PlexAutoLanguages
    environment:
      - TZ=Asia/Kolkata
      - PLEX_URL=
      - PLEX_TOKEN=
    volumes:
      # make sure you have a file named 'config.yaml' in the 'config' dir
      - /root/docker/plexautolanguages/config:/config
    restart: unless-stopped

##############################################################

  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - /root/docker/homarr:/configs
      - /root/docker/homarr:/icons
      - /root/docker/homarr:/data
    ports:
      - '7575:7575'

#############################################################

  plexanisync:
    container_name: plexanisync
    image: 'ghcr.io/rickdb/plexanisync:latest'
    restart: unless-stopped
    environment:
      - PLEX_SECTION=Anime Movies|Anime Shows
      - PLEX_URL=http://127.0.0.1:32400
      - PLEX_TOKEN=
      - ANI_USERNAME=
      - ANI_TOKEN=
      - INTERVAL=3600
    volumes:
      - /etc/localtime:/etc/localtime:ro
#      - '/path/to/your/custom_mappings.yaml:/plexanisync/custom_mappings.yaml'

################################################################

  scheduler:
    image: mcuadros/ofelia:latest
    container_name: scheduler
    restart: unles-stopped
    depends_on:
      - plextraktsync
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      ofelia.job-run.plextraktsync.schedule: "@every 3h"
      ofelia.job-run.plextraktsync.container: "plextraktsync"
